version: '3'

services:
  calendar-service:
    build: .
    container_name: calendar-service
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - DB_HOST=db
      - DB_NAME=reminders
      - DB_USER=postgres
      - DB_PASS=postgres

  db:
    image: 'postgres:13.1-alpine'
    container_name: calendar-service-db
    ports:
      - 5432:5432
    volumes:
      - calendar-service-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=reminders

volumes:
  calendar-service-db:
    external: false
